### ISSUE TITLE
Secure test running orchestration

### ISSUE THREAD

**Issue by hellais** [ooni/orchestra#24]
When we will be rolling out orchestration for the purpose of running tests it's important that we take some extra measures to ensure that it's properly secured.

This is just a brain-dump of what I have in mind on this topic and should probably restructured into a more formal threat model and specification ready for being implemented.

By making it possible for probes to run active tests, if the system is not properly secure, we could potentially expose all our active clients to attacks from some state actor.

The primary threat we want to mitigate against is some state actor compromising OONI servers and being able to orchestrate probes to de-anonymise them or do some undesirable actions.

One thing to keep in mind is that if the "device tokens" used for sending push notifications are compromised an attacker can send push notifications to our probes. These are currently stored in plaintext in the database.

Something that we should look into is the possibility of issuing signed requests for orchestration. These requests would be signed using some hardware security token by the authorised key and the probes would then verify the signature before proceeding to run the measurement. If the orchestration request is either not signed or contains an invalid signature it should be ignored.

For signing the requests we should use something that is fairly standard such as something part of the [JOSE](http://jose.readthedocs.io/en/latest) family (JWT, JWS, etc.).

We should look into how and if it's possible to create a JWS based on some hardware security module like the yubi-key.

Some discussions on this topic happened at the [OONI gathering in berlin](https://github.com/OpenObservatory/gatherings/blob/master/internal/2016-11-berlin/session-ooni-orchestration.md)

**Comment by darkk** [comment]
> part of the JOSE family (JWT, JWS, etc.) ... if it's possible to create a JWS based on some HSM

I'm not 100% sure if JW? is a way to go. Detached PGP signature on some blob may be easier to integrate into MK.

**Comment by hellais** [comment]
> Detached PGP signature on some blob may be easier to integrate into MK.

PGP is a very complex protocol that we probably don't want to have to implement or integrate the terrible libraries out there into MK. `JW*` is on the other hand much simpler and has a variety of libraries for validating and creating them in a multitude of languages.

**Comment by darkk** [comment]
> much simpler

Well, signing "object" sounds like more complex task than signing "blob", JW* also has some history of poor implementations. But, yeah, it may be better than PGP, I'm not familiar with state of GPGME library.

**Comment by hellais** [comment]
> Well, signing "object" sounds like more complex task than signing "blob"

Actually what it signs is just a blob (the base64 encoding of the JSON serialisation of the JSON document).

> JW* also has some history of poor implementations.

Heh, well at least it has many more implementation than PGP to choose from: https://jwt.io/ (44 implementation in 22 different languages)

**Comment by hellais** [comment]
Using a hardware security module to sign a JSON web token: https://connect2id.com/products/nimbus-jose-jwt/examples/pkcs11

**Comment by darkk** [comment]
Some of outcomes of discussion:
- We want to protect our users ⇒ we want to use HSM to store key to sign orchestration requests.
- **Any** person from the [roster](https://github.com/TheTorProject/ooni-spec/blob/master/opos/Measurements-and-url-policy.md#governance-roster) can sign orchestration requests, single signature is enough.
- We want to be able to rotate and revoke keys used to sign orchestration requests ⇒ we need CA to sign keys and deploy new keys over-the-air.
- We are not going to store CA keys in physically protected environment (like bank vault) ⇒ we need two CAs to be protected against accidental key destruction (due to fire, bad water pipes, etc).
- Two distinct persons form the roster should store CA keys.
- CA keys can't be updated, they are compiled into the app. We still can send notification to the user saying "Please, update the app" in case of lost CA key.
- **Revocation** of CA keys **is not possible** as we have no plan for compromised CA key right now :-(
- We should use RSA2048 for signatures as it's most widely adopted by variety of smartcards ([RuToken, FSB-certified](https://www.rutoken.ru/products/catalogue/info_83.html), [OpenPGP card, FSFE-certified](https://github.com/OpenSC/OpenSC/wiki/OpenPGP-card), [Yubikey 4, Google-certified](https://www.yubico.com/products/yubikey-hardware/yubikey4/) and [Yubikey Neo, NFC-enabled one](https://www.yubico.com/products/yubikey-hardware/compare-yubikeys/))

**Comment by hellais** [comment]
More discussions have lead to more conclusions:

* We should drop the idea of having a root CA and instead hardcode the keys of people in the governance roster inside of the app itself.
* Granting somebody rights to orchestration means shipping a new app update
* Revocation means we just pushing a new app update with the new key

I ordered some yubikeys to continue implementing this thing and will put this on hold until they arrive.

**Comment by tomrittervg** [comment]
One of the things to remember is that revocation doesn't work :)  As you note, "Revocation means we just pushing a new app update with the new key" - but you have to plan for people not applying the update. 

This means you'll have part of the population not accepting commands from the new key, and part of the population vulnerable to misuse of the old key (if for example it was compromised.)

You can try adding an expiration date to keys but this assumes that the client has a correct and untamperable clock. (And you still risk orphaning people who don't apply updates.)

---

If you go with JWS and such, make sure you're very careful about not accepting stuff with NONE signatures and only the type of signature you expect - common bug in JWS stuff.

---

Might be a good idea to hardcode a third and keep that one in a safe deposit box or something, just in case two people lose their key. (Again, I'm thinking about the orphaning un-updated poeple problem).

**Comment by hellais** [comment]
@tomrittervg these are good points, thanks for chiming in!

On the topic of Revocation, some of the rational behind going for this simpler option (as opposed to having a CA and having a more complex scheme for dealing with this) is that:

a. Our app update stats show us that we actually have pretty high app update ratios:
   * on Android 89.3% of daily active users (DAU) are on the latest version of the app released on August 10th, with most "updated" users having updated within 24 hours of the release
  * on iOS 82.0% DAU are on the latest version released on August 18th, with also most users having updated within 24 hours of the release

b. Our plan for dealing with a compromised key is that of using message push notifications to inform users of the critical security breach as well as all other communication channels to encourage them to update to the latest version

I don't think in this case adding an expiration date to the keys is optimal as it means that it will ad an extra burden on the mobile team to have to make releases more often to keep up with the key rotation lifecycle. It also doesn't really do that much in the case of a compromised key since the attacker will likely have a sufficiently large window of time to use the compromised key and we would rather focus on making the effort of reaching out to users more effective.

> very careful about not accepting stuff with NONE signatures and only the type of signature you expect

yes I am aware of this "feature" of the JWS spec and noticed that libraries don't actually document this critical caveat that well.

> Might be a good idea to hardcode a third and keep that one in a safe deposit box or something, just in case two people lose their key

This is a very good suggestion. I think we should do it.

**Comment by darkk** [comment]
> you have to plan for people not applying the update

Yep, the vague plan for people not applying the update is
- either BIG SCARY WARNING pushed through orchestration saying that people absolutely must update because some of the keys is compromised
- or kiss-of-death message pushed  through orchestration preventing old clients from being orchestrated (either "at all" or "with some specific key") that is signed either with ANY key from trust store or specifically compromised key (like PGP revocation certificate)

We've not reached consensus yet regarding the method we want to use. Maybe neither of them. In both plans the attacker who compromised the key should also "hack" OONI infrastructure to be able to send messages on behalf of OONI to notification hub. I assume that Apple and Google (who handle significant part of notification infra) may be considered trusted agents as we use theirs app stores to deliver the binary :-)

**Comment by bassosimone** [comment]
> I don't think in this case adding an expiration date to the keys is optimal as it means that it will ad an extra burden on the mobile team to have to make releases more often to keep up with the key rotation lifecycle.

Yes, I agree that the expiration might make our life more complex.

**Comment by hellais** [comment]
We are going to be discontinuing orchestra in the future. We can close this issue as no longer relevant.
